name: EsLint

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Node.JS 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Set Tokens
        run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM }} && npm config set @gsap:registry https://npm.greensock.com/ && npm config set //npm.greensock.com/:_authToken ${{ secrets.GSAP }}

      - name: Install Pnpm
        run: sudo npm -g i pnpm

      - name: Get pnpm cache directory path
        id: pnpm-cache-dir-path
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: |
            ${{ steps.pnpm-cache-dir-path.outputs.STORE_PATH }}
            ~/.cache
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Node Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Test Code Linting
        run: pnpm run lint

      - name: Save Code Linting Report JSON
        run: pnpm run lint:report
        continue-on-error: true

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.0.4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint_report.json"

      - name: Upload ESLint report
        uses: actions/upload-artifact@v1
        with:
          name: eslint_report.json
          path: eslint_report.json
